#redis:
#  restart: always
#  image: redis:latest
#  ports:
#    - "6379:6379"
#  volumes:
#    - redisdata:/data

db:
  restart: always
  image: postgres:9.4
  ports:
    - "5432:5432"
  volumes:
    - ".:/localapp:rw"
    - "./data/backups:/data/backups:rw"

web:
 restart: always
 build: .
 links:
  - "db:postgres"
  #- redis:redis
 env_file: .env
 ports:
  - "8000:8000"
 volumes:
  - ".:/localapp:rw"
  - "./data:/data:rw"
 command: python manage.py runserver 0.0.0.0:8000

