version: "2"

services:

  web:
    restart: always
    build: .
    depends_on:
      - "db"
    #entrypoint: /scripts/wait-for-postgres.sh postgres:5432
    links:
      - "db:postgres"
    ports:
      - "8000:8000"
    volumes:
      - ".:/localapp:rw"
      - "./data:/data:rw"
    command: python manage.py runserver 0.0.0.0:8000

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ".:/localapp:rw"
      - "./data/backups:/data/backups:rw"

