web:
 restart: always
 build: .
 links:
  - "db:postgres"
 env_file: .env
 ports:
  - "8000:8000"
 volumes:
  - ".:/localapp:rw"
  - "./data:/data:rw"
 command: python manage.py runserver 0.0.0.0:8000
